---
title: "GO plot"
author: "Yang & Steve"
date: "01/11/2019"
output: html_document
---

###GO analysis plot

First we need to collect the set of GO terms that we wish to plot, and the genes that belong to each GO term.
These genes were then limited to only those detected as expressed in our data.

```{r}
go2plot <- goResults %>%
    dplyr::filter(shortest_path > 4, DE > 1) %>%
    arrange(P.DE) %>%
    mutate(adjP = p.adjust(P.DE, "bonferroni")) %>%
    dplyr::filter(adjP < 0.05) %>%
  .[["id"]] %>%
  sapply(get, envir = org.Hs.egGO2ALLEGS, simplify = FALSE) %>%
  lapply(intersect, de) %>%
  lapply(unique)
```

Both the GO terms and genes were setup as tibble objects for easier manipulation.

```{r set pathways and genes}
pathwaysGO <- tibble(label = names(go2plot))
genesGO <- go2plot %>%
  unlist() %>%
  unique() %>%
  as.character() %>%
  enframe(name = NULL, value = "label") 
```

Next we need to setup the nodes and edges

```{r set nodes and edges}
nodesGO <- pathwaysGO %>%
  bind_rows(genesGO) %>%
  rowid_to_column("id")
edgesGO <- ldply(go2plot, as.data.frame) %>%
  as_tibble() %>%
  set_colnames(c("pathway", "gene")) %>%
  mutate_all(as.character) %>%
  left_join(nodesGO, by = c("pathway" = "label")) %>%
  dplyr::rename(from = id) %>%
  left_join(nodesGO, by = c("gene" = "label")) %>%
  dplyr::rename(to = id) %>%
  dplyr::select(from, to)
```


```{r}
tidyGO <- tbl_graph(
  nodes = nodesGO,
  edges = edgesGO,
  directed = FALSE
) %>%
  activate(nodes) %>%
  mutate(
    Term = Term(label),
    pathways = case_when(
      label %in% names(go2plot) ~ Term
    ),
    pathways = str_trunc(pathways, 50),
    genes = case_when(
      !label %in% names(go2plot) ~ label
    ),
    # Make the GO terms much larger than the genes
    size = case_when(
      !is.na(pathways) ~ 1000,
      is.na(pathways) ~ 100
    ),
    # Define colours for genes & GO terms
    colour = case_when(
      label %in% names(go2plot) ~ rainbow(max(id))[id],
      !label %in% names(go2plot) ~ "black"
    )
  ) %>%
  activate(edges) %>%
  mutate(
    colour = case_when(
      from <= length(go2plot) ~ rainbow(max(to))[from]
    )
  )
```

```{r GO analysis plot}
set.seed(14)
ggraph(tidyGO, layout = "fr") +
  geom_node_point(
    aes(size = size, colour = colour),
    alpha = 0.5
    ) + 
  geom_edge_arc(
    aes(colour = colour)
  ) + 
  geom_node_label(
     aes(label = pathways),
  repel = TRUE,
    size = 3, 
    alpha = 0.7,
    label.padding = 0.1
  ) +
  theme_graph() +
  theme(
    legend.position = "none"
  )
```
